function error() {
    try {
        aleeeeeert("nofunciona");
    } catch(error) {
        throw new EvalError(["Se ha producido un error",'ej13js.js','3']);
    }
};